{% set name = "demi" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/klauer/demi/archive/v{{ version }}.tar.gz
  sha256:

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9

test:
  imports:
    - demi

about:
  home: https://github.com/klauer/
  doc_url: https://klauer.github.io/klauer/demi
  dev_url: https://github.com/klauer/demi
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: 'de-multiple-inheritance; squash class inheritance'

extra:
  recipe-maintainers:
    - klauer
