
{% set data = load_setup_py_data() %}


package:
    name    : demi

    version : {{ data.get('version') }}


source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.6
      - setuptools

    run:
      - python >=3.6

test:
    imports:
      - demi

    requires:
      - pytest

about:
  home: https://github.com/klauer/demi
  license: SLAC Open License
  summary: de-multiple-inheritance; squash class inheritance
